# Generated by Django 3.2.7 on 2021-09-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
