# Generated by Django 3.2.7 on 2021-09-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0007_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
