# Generated by Django 3.2.7 on 2021-09-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0009_profiledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledetail',
            old_name='img',
            new_name='image',
        ),
    ]
