# Generated by Django 3.2.7 on 2021-09-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0010_rename_img_profiledetail_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileDetail',
        ),
    ]
