# Generated by Django 3.2.7 on 2021-09-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0014_shopcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='order_placed',
            new_name='paid_order',
        ),
    ]
