# Generated by Django 3.2.7 on 2021-09-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0016_rename_order_code_shopcart_cart_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
