# Generated by Django 3.2.7 on 2021-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0019_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='img.jpg', upload_to='category/'),
        ),
    ]
